"""Change secret_key column to LargeBinary

Revision ID: e9151ee357ab
Revises: 65836e4983c1
Create Date: 2025-10-28 13:36:28.539318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9151ee357ab'
down_revision = '65836e4983c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom conversion: Convert existing string secret_keys to bytes
    # Using USING clause to convert varchar to bytea
    op.execute("ALTER TABLE farmers ALTER COLUMN secret_key TYPE bytea USING secret_key::bytea")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert bytea back to varchar
    op.execute("ALTER TABLE farmers ALTER COLUMN secret_key TYPE varchar(255) USING encode(secret_key, 'escape')")
    
    # ### end Alembic commands ###
